#ifndef ADV_ENVIRONMENT_PARAMETERS_GLSL
#define ADV_ENVIRONMENT_PARAMETERS_GLSL

#ifndef ADV_SUN_RADIANCE
#    define ADV_SUN_RADIANCE vec3(1.0)
#endif
#ifndef ADV_MOON_RADIANCE
#    define ADV_MOON_RADIANCE vec3(0.016, 0.02, 0.04)
#endif
#ifndef ADV_SUN_INDIRECT_LIGHT_MULTIPLIER
#    define ADV_SUN_INDIRECT_LIGHT_MULTIPLIER 2.0
#endif
#ifndef ADV_MOON_INDIRECT_LIGHT_MULTIPLIER
#    define ADV_MOON_INDIRECT_LIGHT_MULTIPLIER 8.0
#endif
#ifndef ADV_INDIRECT_LIGHT_STRENGTH
#    define ADV_INDIRECT_LIGHT_STRENGTH 1.0
#endif
#ifndef ADV_BASIC_RADIANCE
#    define ADV_BASIC_RADIANCE 0.0001
#endif
#ifndef ADV_ATMOSPHERE_RG
#    define ADV_ATMOSPHERE_RG 6360000.0
#endif
#ifndef ADV_ATMOSPHERE_RT
#    define ADV_ATMOSPHERE_RT 6460000.0
#endif
#ifndef ADV_ATMOSPHERE_HR
#    define ADV_ATMOSPHERE_HR 8000.0
#endif
#ifndef ADV_ATMOSPHERE_HM
#    define ADV_ATMOSPHERE_HM 1200.0
#endif
#ifndef ADV_ATMOSPHERE_BETA_R
#    define ADV_ATMOSPHERE_BETA_R vec3(0.000005802, 0.000013558, 0.0000331)
#endif
#ifndef ADV_ATMOSPHERE_BETA_M
#    define ADV_ATMOSPHERE_BETA_M vec3(0.000003996)
#endif
#ifndef ADV_ATMOSPHERE_OZONE_ABSORPTION
#    define ADV_ATMOSPHERE_OZONE_ABSORPTION vec3(0.000000650, 0.000001881, 0.000000085)
#endif
#ifndef ADV_ATMOSPHERE_MIE_G
#    define ADV_ATMOSPHERE_MIE_G 0.8
#endif
#ifndef ADV_ATMOSPHERE_MIN_VIEW_COS
#    define ADV_ATMOSPHERE_MIN_VIEW_COS 0.02
#endif

const float ADV_ENVIRONMENT_MAX_DISTANCE = 1000.0;
const vec3 ADV_ENVIRONMENT_AMBIENT = vec3(ADV_BASIC_RADIANCE);

#endif
