#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#define ADV_SCENE_RESOURCES_NO_PREVIOUS_GEOMETRY
#include "scene/resources.glsl"
#include "util/vista.glsl"
#include "scene/hit.glsl"
#include "scene/materials/any_hit.glsl"

#ifndef ADV_CLOUD_MODE
#    define ADV_CLOUD_MODE 1u
#endif

layout(location = 0) rayPayloadInEXT HitPayload hitPayload;
hitAttributeEXT vec2 secondaryHitAttributes;

void main() {
    if (isVistaCovered(worldUBO, gl_InstanceCustomIndexEXT, secondaryHitAttributes)) {
        ignoreIntersectionEXT;
        return;
    }
    AnyHitMaterial material =
        loadAnyHitMaterial(secondaryHitAttributes, hitPayload.coneWidth, hitPayload.coneSpread, false, false);
    if (!material.isCovered || material.isTransparent || material.isWater ||
        (material.isCloud && ADV_CLOUD_MODE != 1u)) {
        ignoreIntersectionEXT;
    }
}
